

services:
  attestation-client:
    image: attestation-suite
    volumes:
      - ../credentials.prepared/attester-client:/app/attestation-suite-config
    container_name: attestation-client-client
    command: attestation-client
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - database

  webserver:
    image: attestation-suite
    volumes:
      - ../credentials.prepared/webserver:/app/attestation-suite-config
    container_name: attestation-client-webserver
    command: webserver
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:3000

  database:
    image: mysql:8-debian
    container_name: attestation-client-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    cap_add:
      - SYS_NICE
    ports:
      - 13306:3306
    volumes:
    #   - ./mysql-conf.d/:/etc/mysql/conf.d
    #   - ./mysql-initdb/:/docker-entrypoint-initdb.d
      - attestation-client-db:/var/lib/mysql

volumes:
  attestation-client-db:
