

services:
  indexer:
    image: attestation-suite
    volumes:
      - ../credentials.prepared/btc-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-btc-indexer
    command: indexer btc
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - database

  verification-server:
    image: attestation-suite
    volumes:
      - ../credentials.prepared/btc-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-btc-verification-server
    command: verification-server btc
    restart: unless-stopped
    environment:
      APP_BASE_PATH: /verifier/btc
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - database
    ports:
      - 9500:9500

  database:
    image: mysql:8-debian
    container_name: indexer-btc-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    cap_add:
      - SYS_NICE
    volumes:
    #   - ./mysql-conf.d/:/etc/mysql/conf.d
    #   - ./mysql-initdb/:/docker-entrypoint-initdb.d
      - indexer-btc-db:/var/lib/mysql

  bitcoin-node:
    image: flarefoundation/bitcoin:23.0
    restart: unless-stopped
    ports:
      - 8332:8332
      - 8333:8333
    volumes:
      - bitcoin-mainnet-data:/opt/bitcoin/.bitcoin/db
      - ../node-configs/mainnet/bitcoin/bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

  spammer:
    image: attestation-suite
    profiles: ["spammer"]
    volumes:
      - ../credentials.prepared/btc-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-btc-spammer
    command: spammer BTC 10000
    restart: unless-stopped

volumes:
  bitcoin-mainnet-data:
  indexer-btc-db:
