

services:
  indexer:
    image: attestation-suite
    volumes:
      - ../credentials.prepared/doge-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-doge-indexer
    command: indexer doge
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - database

  verification-server:
    image: attestation-suite
    volumes:
      - ../credentials.prepared/doge-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-doge-verification-server
    command: verification-server doge
    restart: unless-stopped
    environment:
      APP_BASE_PATH: /verifier/doge
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - database
    ports:
      - 9504:9500

  database:
    image: mysql:8-debian
    container_name: indexer-doge-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    cap_add:
      - SYS_NICE
    volumes:
    #   - ./mysql-conf.d/:/etc/mysql/conf.d
    #   - ./mysql-initdb/:/docker-entrypoint-initdb.d
      - indexer-doge-db:/var/lib/mysql

  dogecoin-node:
    image: flarefoundation/dogecoin:1.14.6
    restart: unless-stopped
    ports:
      - 22555:22555
      - 22556:22556
    volumes:
      - dogecoin-mainnet-data:/opt/dogecoin/.dogecoin/db
      - ../node-configs/mainnet/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

  spammer:
    image: attestation-suite
    profiles: ["spammer"]
    volumes:
      - ../credentials.prepared/doge-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-doge-spammer
    command: spammer DOGE 10000
    restart: unless-stopped

volumes:
  dogecoin-mainnet-data:
  indexer-doge-db:
